login and logout for merchat and guest user
calopter/betsy pull request #8
Opened 2019-10-25 21:26 UTC by sarashahbaig

# bEtsy
Congratulations! You're submitting your assignment! These comprehension questions should be answered by all members of your team, not by a single teammate.

## Comprehension Questions
Question | Answer
:------------- | :-------------
Each team member: what is one thing you were primarily responsible for that you're proud of? | 
Each team member: what is one thing you were primarily responsible for that you would like targeted feedback on? | 
How did your team break up the work to be done? | 
How did your team utilize git to collaborate? | 
What did your group do to try to keep your code DRY while many people collaborated on it? | 
What was a technical challenge that you faced as a group? | 
What was a team/personal challenge that you faced as a group? | 
What was your application's ERD? (include a link) | 
What is your Trello URL? | 
What is the Heroku URL of your deployed application? |

2019-10-25 22:03 UTC, mfunkemomo requested changes

2019-10-25 22:03 UTC, mfunkemomo commented on app/controllers/application_controller.rb
> +    def render_404
Not sure how we'd use this (but I think it's cool). Does this mean in our tests/controllers instead of using `head :not_found`, we can just use `render_404`

2019-10-25 22:03 UTC, mfunkemomo commented on app/controllers/users_controller.rb
> +    def index
Maybe remove if we don't need?

2019-10-25 22:03 UTC, mfunkemomo commented on app/controllers/users_controller.rb
> +      # flash[:status] = :failure
Maybe remove

2019-10-25 22:03 UTC, mfunkemomo commented on app/controllers/users_controller.rb
> +    def login
Should we keep this or remove?

2019-10-25 22:03 UTC, mfunkemomo commented on app/controllers/users_controller.rb
> +    def register
Should we keep this or remove?

2019-10-25 22:03 UTC, mfunkemomo commented on app/controllers/users_controller.rb
> +    def signin
Should we keep this or remove?

2019-10-25 22:03 UTC, mfunkemomo commented on app/models/user.rb
> +    user.username = auth_hash["info"]["email"]
Are we building username as the hash email? I think github has a name or nickname property we'd want to user

2019-10-25 22:03 UTC, mfunkemomo commented on app/views/layouts/application.html.erb
> +          <i class="fas fa-home fa-2x"></i>
is this a bootstrap class name?

2019-10-25 22:03 UTC, mfunkemomo commented on app/views/users/show.html.erb
> +<section class="user-votes__container">
votes?

2019-10-25 22:03 UTC, mfunkemomo commented on db/schema.rb
> +<<<<<<< HEAD
Remove?

2019-10-25 22:03 UTC, mfunkemomo commented on db/schema.rb
> +=======
same, remove?

2019-10-25 22:03 UTC, mfunkemomo commented on db/schema.rb
> +>>>>>>> master
remove?

2019-10-27 16:24 UTC, calopter commented on db/schema.rb
> +<<<<<<< HEAD
these look like there is an unresolved merge conflict committed in the schema, did something happen?

2019-10-27 23:08 UTC, sarashahbaig commented on app/controllers/users_controller.rb
> +      # flash[:status] = :failure
removed

2019-10-27 23:08 UTC, sarashahbaig commented on app/controllers/users_controller.rb
> +    def register
I need that for signup

2019-10-27 23:08 UTC, sarashahbaig commented on app/models/user.rb
> +    user.username = auth_hash["info"]["email"]
changed to nickname but it still worked with email.

2019-10-27 23:08 UTC, sarashahbaig commented on app/views/users/show.html.erb
> +<section class="user-votes__container">
removed

2019-10-28 03:26 UTC, sarashahbaig commented on app/views/layouts/application.html.erb
> +          <i class="fas fa-home fa-2x"></i>
yes

2019-10-28 03:27 UTC, sarashahbaig commented on db/schema.rb
> +<<<<<<< HEAD
resolved

2019-10-28 03:27 UTC, sarashahbaig commented on app/controllers/users_controller.rb
> +    def login
we did that

2019-10-28 03:28 UTC, sarashahbaig commented on app/controllers/users_controller.rb
> +    def index
I need that to view category and product also

2019-10-28 16:44 UTC, closed without merging